import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import products from "../products.json";
import { initiateCheckout } from "../lib/payments";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Avengers Shop App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Avengers Shop</h1>
        <p className={styles.description}>The best avengers swag on the web!</p>

        <ul className={styles.grid}>
          {products.map((product) => {
            const { id, title, image, price, description } = product;
            return (
              <li key={id} className={styles.card}>
                <a href="https://nextjs.org/learn">
                  <Image src={image} alt={title} width="270" height="300" />
                  <h2>{title}</h2>
                  <p>₹ {price}</p>
                  <p>{description}</p>
                </a>
                <p>
                  <button
                    className={styles.button}
                    onClick={() =>
                      initiateCheckout({
                        lineItems: [
                          {
                            price: Id,
                            quantity: 1,
                          },
                        ],
                      })
                    }
                  >
                    Buy Now
                  </button>
                </p>
              </li>
            );
          })}
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
