import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Product from "../products.json";
export default function Home() {
  console.log(Product);
  return (
    <div className={styles.container}>
      <Head>
        <title>Avengers Shop App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Avengers Shop</h1>
        <p className={styles.description}>The best avengers swag on the web!</p>

        <ul className={styles.grid}>
          <li className={styles.card}>
            <a href="https://nextjs.org/learn">
              <img src="/images/hulk_tee.jpeg" alt="avenger tshirt" />
              <h2>Avengers Tshirts</h2>
              <p>
                Bring cosmo the avengers to your wardrobe with this high quality
                tshirt.
              </p>
            </a>
          </li>

          <li className={styles.card}>
            <a href="https://nextjs.org/learn">
              <img src="/images/hulk-sticker.jpeg" alt="avenger tshirt" />
              <h2>Avengers Stickers</h2>
              <p>
                Add some flare to your laptop with a sticker of cosmo the
                avengers
              </p>
            </a>
          </li>
          <li className={styles.card}>
            <a href="https://github.com/vercel/next.js/tree/canary/examples">
              <img src="/images/tee+sticker.jpeg" alt="avenger tshirt" />

              <h2>Avengers Combo</h2>
              <p>
                Show your love for cosmo with a tshirt and sticker combo pack.
              </p>
            </a>
          </li>
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
